### ISSUE TITLE
Ghost's backdoor is erroring

### ISSUE THREAD

**Issue by DaaOtt** [exploderguy/Untitled#18]
[ERROR] gamemodes/untitled/gamemode/modules/ghostsailor/sh_ghostsspookymodule.lu
a:17: attempt to call global 'loadstring' (a nil value)
  1. fn - gamemodes/untitled/gamemode/modules/ghostsailor/sh_ghostsspookymodule.
lua:17
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:183

Fix it please

**Comment by Nyaaaa** [comment]
He fixed it does this need to be open now?
